// Byte-for-byte parity gate: the Dart wallet crypto must reproduce the node's address derivation, HD
// seed-phrase derivation, and transaction hash+signature EXACTLY — using the same committed vectors the
// web wallet's wallet-parity-check.mjs uses (generated by the backend WalletParityVectorsTest). If any
// assertion fails, the node would reject the wallet's transactions; do not ship without 15/15 green.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:wallet/core/crypto/janzeer_crypto.dart';

void main() {
  final v = jsonDecode(File('test/wallet-parity-vectors.json').readAsStringSync()) as Map<String, dynamic>;
  final hd = v['hd'] as Map<String, dynamic>;
  final rawKey = v['rawKey'] as Map<String, dynamic>;
  final t = v['transferTx'] as Map<String, dynamic>;
  final vote = v['voteTx'] as Map<String, dynamic>;
  final promoter = v['promoterTx'] as Map<String, dynamic>;
  final claim = v['claimRewardTx'] as Map<String, dynamic>;

  test('HD derivation: mnemonic -> seed -> m/0/0/0', () {
    expect(bytesToHex(mnemonicToSeed(hd['mnemonic'] as String, passphrase: hd['passphrase'] as String)), hd['seedHex']);
    final acct = accountFromMnemonic(hd['mnemonic'] as String, passphrase: hd['passphrase'] as String);
    expect(acct.privHex, hd['privHex']);
    expect(acct.pubHex, hd['pubHex']);
    expect(acct.address, hd['address']);
  });

  test('raw-key address (known pubkey -> address)', () {
    final acct = accountFromPrivateKey(rawKey['privHex'] as String);
    expect(acct.pubHex, rawKey['pubHex']);
    expect(acct.address, rawKey['address']);
  });

  test('TransferTx preimage + hash + signature (byte-identical)', () {
    final payload = transferPayload(amount: t['amount'] as String, recipientAddress: t['recipientAddress'] as String, data: t['data'] as String);
    final preimage = transactionBytes(
        timestamp: t['timestamp'] as int, fee: t['fee'] as String, nonce: t['nonce'] as int,
        senderAddress: t['senderAddress'] as String, payload: payload);
    expect(bytesToHex(preimage), t['preimageHex']);
    final hash = hashBytes(preimage);
    expect(hash, t['hash']);
    expect(signHash(hash, rawKey['privHex'] as String), t['signature']);
  });

  test('VoteTx hash + signature', () {
    final s = buildSignedVote(
        timestamp: vote['timestamp'] as int, fee: vote['fee'] as String, nonce: vote['nonce'] as int,
        senderAddress: vote['senderAddress'] as String, publicKey: vote['publicKey'] as String,
        voteTypeId: vote['voteTypeId'] as int, promoterKey: vote['promoterKey'] as String, privHex: rawKey['privHex'] as String);
    expect(s['hash'], vote['hash']);
    expect(s['senderSignature'], vote['signature']);
  });

  test('PromoterTx hash + signature', () {
    final s = buildSignedPromoter(
        timestamp: promoter['timestamp'] as int, fee: promoter['fee'] as String, nonce: promoter['nonce'] as int,
        senderAddress: promoter['senderAddress'] as String, publicKey: promoter['publicKey'] as String,
        amount: promoter['amount'] as String, promoterKey: promoter['promoterKey'] as String, privHex: rawKey['privHex'] as String);
    expect(s['hash'], promoter['hash']);
    expect(s['senderSignature'], promoter['signature']);
  });

  test('ClaimRewardTx hash + signature', () {
    final s = buildSignedClaimReward(
        timestamp: claim['timestamp'] as int, fee: claim['fee'] as String, nonce: claim['nonce'] as int,
        senderAddress: claim['senderAddress'] as String, publicKey: claim['publicKey'] as String, privHex: rawKey['privHex'] as String);
    expect(s['hash'], claim['hash']);
    expect(s['senderSignature'], claim['signature']);
  });
}
