// Byte-for-byte parity gate: the Dart wallet crypto must reproduce the node's address derivation, HD
// seed-phrase derivation, and transaction hash+signature EXACTLY — using the same committed vectors the
// web wallet's wallet-parity-check.mjs uses (generated by the backend WalletParityVectorsTest). If any
// assertion fails, the node would reject the wallet's transactions; do not ship without 15/15 green.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:wallet/core/crypto/janzeer_crypto.dart';

void main() {
  final v = jsonDecode(File('test/wallet-parity-vectors.json').readAsStringSync()) as Map<String, dynamic>;
  final hd = v['hd'] as Map<String, dynamic>;
  final rawKey = v['rawKey'] as Map<String, dynamic>;
  final t = v['transferTx'] as Map<String, dynamic>;
  final promoter = v['promoterTx'] as Map<String, dynamic>;
  final exit = v['exitPromoterTx'] as Map<String, dynamic>;
  final tc = v['tokenCreateTx'] as Map<String, dynamic>;
  final tt = v['tokenTransferTx'] as Map<String, dynamic>;

  test('HD derivation: mnemonic -> seed -> m/0/0/0', () {
    expect(bytesToHex(mnemonicToSeed(hd['mnemonic'] as String, passphrase: hd['passphrase'] as String)), hd['seedHex']);
    final acct = accountFromMnemonic(hd['mnemonic'] as String, passphrase: hd['passphrase'] as String);
    expect(acct.privHex, hd['privHex']);
    expect(acct.pubHex, hd['pubHex']);
    expect(acct.address, hd['address']);
  });

  test('raw-key address (known pubkey -> address)', () {
    final acct = accountFromPrivateKey(rawKey['privHex'] as String);
    expect(acct.pubHex, rawKey['pubHex']);
    expect(acct.address, rawKey['address']);
  });

  test('TransferTx preimage + hash + signature (byte-identical)', () {
    final payload = transferPayload(amount: t['amount'] as String, recipientAddress: t['recipientAddress'] as String, data: t['data'] as String);
    final preimage = transactionBytes(
        timestamp: t['timestamp'] as int, fee: t['fee'] as String, nonce: t['nonce'] as int,
        senderAddress: t['senderAddress'] as String, payload: payload);
    expect(bytesToHex(preimage), t['preimageHex']);
    final hash = hashBytes(preimage);
    expect(hash, t['hash']);
    expect(signHash(hash, rawKey['privHex'] as String), t['signature']);
  });

  test('PromoterTx hash + signature', () {
    final s = buildSignedPromoter(
        timestamp: promoter['timestamp'] as int, fee: promoter['fee'] as String, nonce: promoter['nonce'] as int,
        senderAddress: promoter['senderAddress'] as String, publicKey: promoter['publicKey'] as String,
        amount: promoter['amount'] as String, promoterKey: promoter['promoterKey'] as String, privHex: rawKey['privHex'] as String);
    expect(s['hash'], promoter['hash']);
    expect(s['senderSignature'], promoter['signature']);
  });

  test('ExitPromoterTx hash + signature', () {
    final s = buildSignedExitPromoter(
        timestamp: exit['timestamp'] as int, fee: exit['fee'] as String, nonce: exit['nonce'] as int,
        senderAddress: exit['senderAddress'] as String, publicKey: exit['publicKey'] as String,
        promoterKey: exit['promoterKey'] as String, privHex: rawKey['privHex'] as String);
    expect(s['hash'], exit['hash']);
    expect(s['senderSignature'], exit['signature']);
  });

  Uint8List tokenPayloadOf(Map<String, dynamic> x) => tokenPayload(
        op: x['op'] as int, tokenId: x['tokenId'] as String, symbol: x['symbol'] as String,
        name: x['name'] as String, decimals: x['decimals'] as int,
        cap: x['cap'] as String?, amount: x['amount'] as String?, recipient: x['recipient'] as String?,
      );
  Map<String, Object?> buildTokenOf(Map<String, dynamic> x) => buildSignedTokenTx(
        timestamp: x['timestamp'] as int, fee: x['fee'] as String, nonce: x['nonce'] as int,
        senderAddress: x['senderAddress'] as String, publicKey: x['publicKey'] as String,
        op: x['op'] as int, tokenId: x['tokenId'] as String, symbol: x['symbol'] as String,
        name: x['name'] as String, decimals: x['decimals'] as int,
        cap: x['cap'] as String?, amount: x['amount'] as String?, recipient: x['recipient'] as String?,
        privHex: rawKey['privHex'] as String,
      );

  test('TokenTx CREATE preimage + hash + signature (byte-identical)', () {
    final preimage = transactionBytes(
        timestamp: tc['timestamp'] as int, fee: tc['fee'] as String, nonce: tc['nonce'] as int,
        senderAddress: tc['senderAddress'] as String, payload: tokenPayloadOf(tc));
    expect(bytesToHex(preimage), tc['preimageHex']);
    final s = buildTokenOf(tc);
    expect(s['hash'], tc['hash']);
    expect(s['senderSignature'], tc['signature']);
  });

  test('TokenTx TRANSFER preimage + hash + signature (byte-identical)', () {
    final preimage = transactionBytes(
        timestamp: tt['timestamp'] as int, fee: tt['fee'] as String, nonce: tt['nonce'] as int,
        senderAddress: tt['senderAddress'] as String, payload: tokenPayloadOf(tt));
    expect(bytesToHex(preimage), tt['preimageHex']);
    final s = buildTokenOf(tt);
    expect(s['hash'], tt['hash']);
    expect(s['senderSignature'], tt['signature']);
  });

  test('EIP-55 checksum overlay (display only; canonical stays lowercase)', () {
    // Canonical address (what gets signed) is lowercase; the checksum form validates but never changes bytes.
    expect(isChecksumValid(rawKey['address'] as String), isTrue);
    expect(toChecksumAddress(rawKey['address'] as String).toLowerCase(), rawKey['address']);
  });
}
